server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  location / { try_files $uri $uri/ /index.html; }
  location /api/     { proxy_pass http://pipeline:3000/api/;  proxy_read_timeout 900s; }
  location /metrics  { proxy_pass http://pipeline:3000/metrics; }
  location /health   { proxy_pass http://pipeline:3000/health; }
  location /chaos/   { proxy_pass http://chaos:3002/; }
  location /consumer/ { proxy_pass http://consumer:3001/; }
}
